config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :manages
  resources :grades
  resources :papers do
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  # Homepage
  get 'contact', to: 'homepage#contact', as: 'contact'
  get 'about', to: 'homepage#about', as: 'about'

  get 'paperlist', to: 'papers#index', as: 'paperlist'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For Admin user
  get 'addpaper', to: 'papers#index', as: 'addpaper'
  get 'removepaper', to: 'papers#index', as: 'removepaper'
  get 'managepapers', to: 'manages#index', as: 'managepapers'
  get 'set', to: 'manages#edit', as: 'set'
  
  # For Elevated user

  # For Normal user
  post 'createscore', to: 'scores#create', as: 'createscore'
  
  root 'homepage#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:user_id, :paper_id, :feasibility, :novelty, :significance, :quality, :comment)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :paper_id %>
    <%= form.number_field :paper_id %>
  </div>

  <div class="field">
    <%= form.label :feasibility %>
    <%= form.number_field :feasibility %>
  </div>

  <div class="field">
    <%= form.label :novelty %>
    <%= form.number_field :novelty %>
  </div>

  <div class="field">
    <%= form.label :significance %>
    <%= form.number_field :significance %>
  </div>

  <div class="field">
    <%= form.label :quality %>
    <%= form.number_field :quality %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Paper</th>
      <th>Feasibility</th>
      <th>Novelty</th>
      <th>Significance</th>
      <th>Quality</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.user_id %></td>
        <td><%= score.paper_id %></td>
        <td><%= score.feasibility %></td>
        <td><%= score.novelty %></td>
        <td><%= score.significance %></td>
        <td><%= score.quality %></td>
        <td><%= score.comment %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>Paper:</strong>
  <%= @score.paper_id %>
</p>

<p>
  <strong>Feasibility:</strong>
  <%= @score.feasibility %>
</p>

<p>
  <strong>Novelty:</strong>
  <%= @score.novelty %>
</p>

<p>
  <strong>Significance:</strong>
  <%= @score.significance %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @score.quality %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @score.comment %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>