config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :manages
  resources :grades
  resources :papers do
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  # Homepage
  get 'contact', to: 'homepage#contact', as: 'contact'
  get 'about', to: 'homepage#about', as: 'about'

  get 'paperlist', to: 'papers#index', as: 'paperlist'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For Admin user
  get 'addpaper', to: 'papers#index', as: 'addpaper'
  get 'removepaper', to: 'papers#index', as: 'removepaper'
  get 'managepapers', to: 'manages#index', as: 'managepapers'
  get 'set', to: 'manages#edit', as: 'set'
  
  # For Elevated user

  # For Normal user
  post 'createscore', to: 'scores#create', as: 'createscore'
  
  root 'homepage#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/manage.rb
class Manage < ApplicationRecord
end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  before_action :set_manage, only: [:show, :edit, :update, :destroy]

  # GET /manages
  # GET /manages.json
  def index
    @manages = Manage.all
  end

  # GET /manages/1
  # GET /manages/1.json
  def show
  end

  # GET /manages/new
  def new
    @manage = Manage.new
  end

  # GET /manages/1/edit
  def edit
    @to_set = params[:to_set]
  end

  # POST /manages
  # POST /manages.json
  def create
    @manage = Manage.new(manage_params)

    respond_to do |format|
      if @manage.save
        format.html { redirect_to @manage, notice: 'Manage was successfully created.' }
        format.json { render :show, status: :created, location: @manage }
      else
        format.html { render :new }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manages/1
  # PATCH/PUT /manages/1.json
  def update
    respond_to do |format|
      if @manage.update(manage_params)
        format.html { redirect_to @manage, notice: 'Manage was successfully updated.' }
        format.json { render :show, status: :ok, location: @manage }
      else
        format.html { render :edit }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manages/1
  # DELETE /manages/1.json
  def destroy
    @manage.destroy
    respond_to do |format|
      format.html { redirect_to manages_url, notice: 'Manage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage
      @manage = Manage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manage_params
      params.require(:manage).permit(:deadline, :review_ungraded, :update_graded)
    end
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/views/manages/_form.html.erb
<%= form_with(model: manage, local: true) do |form| %>
  <% if manage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manage.errors.count, "error") %> prohibited this manage from being saved:</h2>

      <ul>
        <% manage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :review_ungraded %>
    <%= form.check_box :review_ungraded %>
  </div>

  <div class="field">
    <%= form.label :update_graded %>
    <%= form.check_box :update_graded %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manages/edit.html.erb
<% if @to_set == "set_deadline" %>
  <h1>SET DEADLINE</h1>
<% elsif %>
  <h1>DISABLE SCORING</h1>
<% end %>

<%= form_with(model: @manage, local: true) do |form| %>
  <% if @manage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manage.errors.count, "error") %> prohibited this manage from being saved:</h2>

      <ul>
        <% @manage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @to_set == "set_deadline" %>
    <div class="field">
      <%= form.datetime_select :deadline %>
    </div>
  <% end %>
  
  <% if @to_set == "disable_scoring" %>
    <div class="field">
      <%= form.check_box :review_ungraded %> REVIEW OF UNGRADED PAPERS
    </div>
  <% end %>
  
  <% if @to_set == "disable_scoring" %>
    <div class="field">
      <%= form.check_box :update_graded %> SCORE UPDATE OF GRADED PAPERS
    </div>
  <% end %>
  
  <% if @to_set %>
    <div class="actions">
      <%= form.submit "CONFIRM"%>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', manages_path %>

app/views/manages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manages</h1>

<% manage = @manages.first %>
<%= link_to 'SET DEADLINE', edit_manage_path(manage, to_set:"set_deadline") %>
<br>
<%= link_to 'DISABLE SCORING', edit_manage_path(manage, to_set:"disable_scoring") %>
<br>
<%= link_to 'SORT PAPERS', edit_manage_path(manage) %>

<br>


<%= link_to 'New Manage', new_manage_path %>

app/views/manages/new.html.erb
<h1>New Manage</h1>

<%= render 'form', manage: @manage %>

<%= link_to 'Back', manages_path %>

app/views/manages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deadline:</strong>
  <%= @manage.deadline %>
</p>

<p>
  <strong>Review ungraded:</strong>
  <%= @manage.review_ungraded %>
</p>

<p>
  <strong>Update graded:</strong>
  <%= @manage.update_graded %>
</p>

<%= link_to 'Edit', edit_manage_path(@manage) %> |
<%= link_to 'Back', addpaper_path %>