config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :manages
  resources :grades
  resources :papers do
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  # Homepage
  get 'contact', to: 'homepage#contact', as: 'contact'
  get 'about', to: 'homepage#about', as: 'about'

  get 'paperlist', to: 'papers#index', as: 'paperlist'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For Admin user
  get 'addpaper', to: 'papers#index', as: 'addpaper'
  get 'removepaper', to: 'papers#index', as: 'removepaper'
  get 'managepapers', to: 'manages#index', as: 'managepapers'
  get 'set', to: 'manages#edit', as: 'set'
  
  # For Elevated user

  # For Normal user
  post 'createscore', to: 'scores#create', as: 'createscore'
  
  root 'homepage#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :Scores
  has_many :Users, :through => :Scores 
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
    @scores = Score.find_by(user_id: current_user.id)
    @manage_paper = params[:manage_paper]
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :author, :link)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<!--
  <%= notice %>
-->

<!--- Unique Contents here -->
<div id="viewlist" class="container" style="float: left; padding: 1%; width: 80%; overflow: hidden; border: 1px solid #000;">
  <h2>Papers</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Link</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.author %></td>
        <td><%= paper.link %></td>
        <% if @manage_paper == "add" %>
          <td><%= link_to 'Show', paper %></td>
          <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <% elsif @manage_paper == "remove" %>
          <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  <br>
  <% if @manage_paper == "add" %>
    <%= link_to 'New Paper', new_paper_path, :class => "nav-link"%>
  <% end %>
</div>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @paper.author %>
</p>

<p>
  <strong>Link:</strong>
  <%= @paper.link %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>